from AnalysisAlgorithmsConfig.ConfigBlock import ConfigBlock

truth_branches = {
    "Ttbar" : [
        'MC_ttbar_beforeFSR_pt',
        'MC_ttbar_beforeFSR_eta',
        'MC_ttbar_beforeFSR_phi',
        'MC_ttbar_beforeFSR_m',
        'MC_ttbar_afterFSR_beforeDecay_pt',
        'MC_ttbar_afterFSR_beforeDecay_eta',
        'MC_ttbar_afterFSR_beforeDecay_phi',
        'MC_ttbar_afterFSR_beforeDecay_m',
        'MC_ttbar_afterFSR_pt',
        'MC_ttbar_afterFSR_eta',
        'MC_ttbar_afterFSR_phi',
        'MC_ttbar_afterFSR_m',
        'MC_t_beforeFSR_pt',
        'MC_t_beforeFSR_eta',
        'MC_t_beforeFSR_phi',
        'MC_t_beforeFSR_m',
        'MC_t_afterFSR_pt',
        'MC_t_afterFSR_eta',
        'MC_t_afterFSR_phi',
        'MC_t_afterFSR_m',
        'MC_t_afterFSR_SC_pt',
        'MC_t_afterFSR_SC_eta',
        'MC_t_afterFSR_SC_phi',
        'MC_t_afterFSR_SC_m',
        'MC_W_from_t_pt',
        'MC_W_from_t_eta',
        'MC_W_from_t_phi',
        'MC_W_from_t_m',
        'MC_b_from_t_pt',
        'MC_b_from_t_eta',
        'MC_b_from_t_phi',
        'MC_b_from_t_m',
        'MC_Wdecay1_from_t_pt',
        'MC_Wdecay1_from_t_eta',
        'MC_Wdecay1_from_t_phi',
        'MC_Wdecay1_from_t_m',
        'MC_Wdecay1_from_t_pdgId',
        'MC_Wdecay2_from_t_pt',
        'MC_Wdecay2_from_t_eta',
        'MC_Wdecay2_from_t_phi',
        'MC_Wdecay2_from_t_m',
        'MC_Wdecay2_from_t_pdgId',
        'MC_tbar_beforeFSR_pt',
        'MC_tbar_beforeFSR_eta',
        'MC_tbar_beforeFSR_phi',
        'MC_tbar_beforeFSR_m',
        'MC_tbar_afterFSR_pt',
        'MC_tbar_afterFSR_eta',
        'MC_tbar_afterFSR_phi',
        'MC_tbar_afterFSR_m',
        'MC_tbar_afterFSR_SC_pt',
        'MC_tbar_afterFSR_SC_eta',
        'MC_tbar_afterFSR_SC_phi',
        'MC_tbar_afterFSR_SC_m',
        'MC_W_from_tbar_pt',
        'MC_W_from_tbar_eta',
        'MC_W_from_tbar_phi',
        'MC_W_from_tbar_m',
        'MC_b_from_tbar_pt',
        'MC_b_from_tbar_eta',
        'MC_b_from_tbar_phi',
        'MC_b_from_tbar_m',
        'MC_Wdecay1_from_tbar_pt',
        'MC_Wdecay1_from_tbar_eta',
        'MC_Wdecay1_from_tbar_phi',
        'MC_Wdecay1_from_tbar_m',
        'MC_Wdecay1_from_tbar_pdgId',
        'MC_Wdecay2_from_tbar_pt',
        'MC_Wdecay2_from_tbar_eta',
        'MC_Wdecay2_from_tbar_phi',
        'MC_Wdecay2_from_tbar_m',
        'MC_Wdecay2_from_tbar_pdgId'
    ],
    "TtbarLight": [
        'MC_ttbar_beforeFSR_pt',
        'MC_ttbar_beforeFSR_eta',
        'MC_ttbar_beforeFSR_phi',
        'MC_ttbar_beforeFSR_m',
        'MC_ttbar_afterFSR_pt',
        'MC_ttbar_afterFSR_eta',
        'MC_ttbar_afterFSR_phi',
        'MC_ttbar_afterFSR_m',
        'MC_t_beforeFSR_pt',
        'MC_t_beforeFSR_eta',
        'MC_t_beforeFSR_phi',
        'MC_t_beforeFSR_m',
        'MC_t_afterFSR_pt',
        'MC_t_afterFSR_eta',
        'MC_t_afterFSR_phi',
        'MC_t_afterFSR_m',
        'MC_t_afterFSR_SC_pt',
        'MC_t_afterFSR_SC_eta',
        'MC_t_afterFSR_SC_phi',
        'MC_t_afterFSR_SC_m',
        'MC_W_from_t_pt',
        'MC_W_from_t_eta',
        'MC_W_from_t_phi',
        'MC_W_from_t_m',
        'MC_q_from_t_pt',
        'MC_q_from_t_eta',
        'MC_q_from_t_phi',
        'MC_q_from_t_m',
        'MC_q_from_t_pdgId',
        'MC_Wdecay1_from_t_pt',
        'MC_Wdecay1_from_t_eta',
        'MC_Wdecay1_from_t_phi',
        'MC_Wdecay1_from_t_m',
        'MC_Wdecay1_from_t_pdgId',
        'MC_Wdecay2_from_t_pt',
        'MC_Wdecay2_from_t_eta',
        'MC_Wdecay2_from_t_phi',
        'MC_Wdecay2_from_t_m',
        'MC_Wdecay2_from_t_pdgId',
        'MC_tbar_beforeFSR_pt',
        'MC_tbar_beforeFSR_eta',
        'MC_tbar_beforeFSR_phi',
        'MC_tbar_beforeFSR_m',
        'MC_tbar_afterFSR_pt',
        'MC_tbar_afterFSR_eta',
        'MC_tbar_afterFSR_phi',
        'MC_tbar_afterFSR_m',
        'MC_tbar_afterFSR_SC_pt',
        'MC_tbar_afterFSR_SC_eta',
        'MC_tbar_afterFSR_SC_phi',
        'MC_tbar_afterFSR_SC_m',
        'MC_W_from_tbar_pt',
        'MC_W_from_tbar_eta',
        'MC_W_from_tbar_phi',
        'MC_W_from_tbar_m',
        'MC_q_from_tbar_pt',
        'MC_q_from_tbar_eta',
        'MC_q_from_tbar_phi',
        'MC_q_from_tbar_m',
        'MC_q_from_tbar_pdgId',
        'MC_Wdecay1_from_tbar_pt',
        'MC_Wdecay1_from_tbar_eta',
        'MC_Wdecay1_from_tbar_phi',
        'MC_Wdecay1_from_tbar_m',
        'MC_Wdecay1_from_tbar_pdgId',
        'MC_Wdecay2_from_tbar_pt',
        'MC_Wdecay2_from_tbar_eta',
        'MC_Wdecay2_from_tbar_phi',
        'MC_Wdecay2_from_tbar_m',
        'MC_Wdecay2_from_tbar_pdgId'
    ],
    "TTZ" : [
        'MC_ttbar_beforeFSR_pt',
        'MC_ttbar_beforeFSR_eta',
        'MC_ttbar_beforeFSR_phi',
        'MC_ttbar_beforeFSR_m',
        'MC_ttbar_afterFSR_beforeDecay_pt',
        'MC_ttbar_afterFSR_beforeDecay_eta',
        'MC_ttbar_afterFSR_beforeDecay_phi',
        'MC_ttbar_afterFSR_beforeDecay_m',
        'MC_ttbar_afterFSR_pt',
        'MC_ttbar_afterFSR_eta',
        'MC_ttbar_afterFSR_phi',
        'MC_ttbar_afterFSR_m',
        'MC_t_beforeFSR_pt',
        'MC_t_beforeFSR_eta',
        'MC_t_beforeFSR_phi',
        'MC_t_beforeFSR_m',
        'MC_t_afterFSR_pt',
        'MC_t_afterFSR_eta',
        'MC_t_afterFSR_phi',
        'MC_t_afterFSR_m',
        'MC_t_afterFSR_SC_pt',
        'MC_t_afterFSR_SC_eta',
        'MC_t_afterFSR_SC_phi',
        'MC_t_afterFSR_SC_m',
        'MC_W_from_t_pt',
        'MC_W_from_t_eta',
        'MC_W_from_t_phi',
        'MC_W_from_t_m',
        'MC_b_from_t_pt',
        'MC_b_from_t_eta',
        'MC_b_from_t_phi',
        'MC_b_from_t_m',
        'MC_Wdecay1_from_t_pt',
        'MC_Wdecay1_from_t_eta',
        'MC_Wdecay1_from_t_phi',
        'MC_Wdecay1_from_t_m',
        'MC_Wdecay1_from_t_pdgId',
        'MC_Wdecay2_from_t_pt',
        'MC_Wdecay2_from_t_eta',
        'MC_Wdecay2_from_t_phi',
        'MC_Wdecay2_from_t_m',
        'MC_Wdecay2_from_t_pdgId',
        'MC_tbar_beforeFSR_pt',
        'MC_tbar_beforeFSR_eta',
        'MC_tbar_beforeFSR_phi',
        'MC_tbar_beforeFSR_m',
        'MC_tbar_afterFSR_pt',
        'MC_tbar_afterFSR_eta',
        'MC_tbar_afterFSR_phi',
        'MC_tbar_afterFSR_m',
        'MC_tbar_afterFSR_SC_pt',
        'MC_tbar_afterFSR_SC_eta',
        'MC_tbar_afterFSR_SC_phi',
        'MC_tbar_afterFSR_SC_m',
        'MC_W_from_tbar_pt',
        'MC_W_from_tbar_eta',
        'MC_W_from_tbar_phi',
        'MC_W_from_tbar_m',
        'MC_b_from_tbar_pt',
        'MC_b_from_tbar_eta',
        'MC_b_from_tbar_phi',
        'MC_b_from_tbar_m',
        'MC_Wdecay1_from_tbar_pt',
        'MC_Wdecay1_from_tbar_eta',
        'MC_Wdecay1_from_tbar_phi',
        'MC_Wdecay1_from_tbar_m',
        'MC_Wdecay1_from_tbar_pdgId',
        'MC_Wdecay2_from_tbar_pt',
        'MC_Wdecay2_from_tbar_eta',
        'MC_Wdecay2_from_tbar_phi',
        'MC_Wdecay2_from_tbar_m',
        'MC_Wdecay2_from_tbar_pdgId',
        'MC_Z_pt',
        'MC_Z_eta',
        'MC_Z_phi',
        'MC_Z_m',
        'MC_Zdecay1_pt',
        'MC_Zdecay1_eta',
        'MC_Zdecay1_phi',
        'MC_Zdecay1_m',
        'MC_Zdecay1_pdgId',
        'MC_Zdecay2_pt',
        'MC_Zdecay2_eta',
        'MC_Zdecay2_phi',
        'MC_Zdecay2_m',
        'MC_Zdecay2_pdgId',
        'MC_Z_IsOnShell',
        'MC_Z_AncestryCorrupted'
    ],
    "Tth" : [
        'MC_ttbar_beforeFSR_pt',
        'MC_ttbar_beforeFSR_eta',
        'MC_ttbar_beforeFSR_phi',
        'MC_ttbar_beforeFSR_m',
        'MC_ttbar_afterFSR_beforeDecay_pt',
        'MC_ttbar_afterFSR_beforeDecay_eta',
        'MC_ttbar_afterFSR_beforeDecay_phi',
        'MC_ttbar_afterFSR_beforeDecay_m',
        'MC_ttbar_afterFSR_pt',
        'MC_ttbar_afterFSR_eta',
        'MC_ttbar_afterFSR_phi',
        'MC_ttbar_afterFSR_m',
        'MC_t_beforeFSR_pt',
        'MC_t_beforeFSR_eta',
        'MC_t_beforeFSR_phi',
        'MC_t_beforeFSR_m',
        'MC_t_afterFSR_pt',
        'MC_t_afterFSR_eta',
        'MC_t_afterFSR_phi',
        'MC_t_afterFSR_m',
        'MC_t_afterFSR_SC_pt',
        'MC_t_afterFSR_SC_eta',
        'MC_t_afterFSR_SC_phi',
        'MC_t_afterFSR_SC_m',
        'MC_W_from_t_pt',
        'MC_W_from_t_eta',
        'MC_W_from_t_phi',
        'MC_W_from_t_m',
        'MC_b_from_t_pt',
        'MC_b_from_t_eta',
        'MC_b_from_t_phi',
        'MC_b_from_t_m',
        'MC_Wdecay1_from_t_pt',
        'MC_Wdecay1_from_t_eta',
        'MC_Wdecay1_from_t_phi',
        'MC_Wdecay1_from_t_m',
        'MC_Wdecay1_from_t_pdgId',
        'MC_Wdecay2_from_t_pt',
        'MC_Wdecay2_from_t_eta',
        'MC_Wdecay2_from_t_phi',
        'MC_Wdecay2_from_t_m',
        'MC_Wdecay2_from_t_pdgId',
        'MC_tbar_beforeFSR_pt',
        'MC_tbar_beforeFSR_eta',
        'MC_tbar_beforeFSR_phi',
        'MC_tbar_beforeFSR_m',
        'MC_tbar_afterFSR_pt',
        'MC_tbar_afterFSR_eta',
        'MC_tbar_afterFSR_phi',
        'MC_tbar_afterFSR_m',
        'MC_tbar_afterFSR_SC_pt',
        'MC_tbar_afterFSR_SC_eta',
        'MC_tbar_afterFSR_SC_phi',
        'MC_tbar_afterFSR_SC_m',
        'MC_W_from_tbar_pt',
        'MC_W_from_tbar_eta',
        'MC_W_from_tbar_phi',
        'MC_W_from_tbar_m',
        'MC_b_from_tbar_pt',
        'MC_b_from_tbar_eta',
        'MC_b_from_tbar_phi',
        'MC_b_from_tbar_m',
        'MC_Wdecay1_from_tbar_pt',
        'MC_Wdecay1_from_tbar_eta',
        'MC_Wdecay1_from_tbar_phi',
        'MC_Wdecay1_from_tbar_m',
        'MC_Wdecay1_from_tbar_pdgId',
        'MC_Wdecay2_from_tbar_pt',
        'MC_Wdecay2_from_tbar_eta',
        'MC_Wdecay2_from_tbar_phi',
        'MC_Wdecay2_from_tbar_m',
        'MC_Wdecay2_from_tbar_pdgId',
        'MC_Higgs_pt',
        'MC_Higgs_eta',
        'MC_Higgs_phi',
        'MC_Higgs_m',
        'MC_Higgs_decay1_pt',
        'MC_Higgs_decay1_eta',
        'MC_Higgs_decay1_phi',
        'MC_Higgs_decay1_m',
        'MC_Higgs_decay1_pdgId',
        'MC_Higgs_tau_decay1_isHadronic',
        'MC_Higgs_decay2_pt',
        'MC_Higgs_decay2_eta',
        'MC_Higgs_decay2_phi',
        'MC_Higgs_decay2_m',
        'MC_Higgs_decay2_pdgId',
        'MC_Higgs_tau_decay2_isHadronic',
        'MC_Higgs_decay1_from_decay1_pt',
        'MC_Higgs_decay1_from_decay1_eta',
        'MC_Higgs_decay1_from_decay1_phi',
        'MC_Higgs_decay1_from_decay1_m',
        'MC_Higgs_decay1_from_decay1_pdgId',
        'MC_Higgs_tau_decay1_from_decay1_isHadronic',
        'MC_Higgs_decay2_from_decay1_pt',
        'MC_Higgs_decay2_from_decay1_eta',
        'MC_Higgs_decay2_from_decay1_phi',
        'MC_Higgs_decay2_from_decay1_m',
        'MC_Higgs_decay2_from_decay1_pdgId',
        'MC_Higgs_tau_decay2_from_decay1_isHadronic',
        'MC_Higgs_decay1_from_decay2_pt',
        'MC_Higgs_decay1_from_decay2_eta',
        'MC_Higgs_decay1_from_decay2_phi',
        'MC_Higgs_decay1_from_decay2_m',
        'MC_Higgs_decay1_from_decay2_pdgId',
        'MC_Higgs_tau_decay1_from_decay2_isHadronic',
        'MC_Higgs_decay2_from_decay2_pt',
        'MC_Higgs_decay2_from_decay2_eta',
        'MC_Higgs_decay2_from_decay2_phi',
        'MC_Higgs_decay2_from_decay2_m',
        'MC_Higgs_decay2_from_decay2_pdgId',
        'MC_Higgs_tau_decay2_from_decay2_isHadronic',
    ],
}

class truthConfig(ConfigBlock):
    """ConfigBlock for truth/parton-level objects"""

    def __init__(self):
        super(truthConfig, self).__init__('partonLevel')
        self.addOption('histories', None, type=str)

    def makeAlgs(self, config):
        # loop over all histories
        for history in self.getPartonHistories():
            alg = config.createAlgorithm("top::RunPartonHistoryAlg", "TopPartonHistory" + history)
            alg.topPartonScheme = history

            container = "TopPartonHistory" + history
            config.setSourceName(container, container)
            config.addOutputContainer(container, container)

            for branch in truth_branches[history]:
                config.addOutputVar(container, branch, branch, noSys=True)

    def getPartonHistories(self):
        # parton histories can be provided as History1.History2.etc
        return self.histories.split(".")

    def getOutputContainers(self):
        # return a dictionary of containers that can be added to the OutputAnalysisConfig
        containerDict = {}
        for history in self.getPartonHistories():
            containerDict[history + '_'] = 'TopPartonHistory' + history

        return containerDict
