include:
# GENERATE THE DOCS
    - project: 'authoring/documentation/mkdocs-ci'
      file: 'mkdocs-gitlab-pages.gitlab-ci.yml'
# CREATE NEW RELEASES TO MATCH TAGS
    - '/.gitlab/ci_templates/release_on_tag.yml'
