stages:
  - run

variables:
  RUN_DIR: run
  RUN_DIR_ABS: ${CI_PROJECT_DIR}/${RUN_DIR}

.prepare_dirs: &prepare_dirs
  - mkdir ${JOBNAME}
  - cd ${JOBNAME}
  - set +e

.restore_environment: &restore_environment
  - set +e
  - source ${CI_PROJECT_DIR}/.gitlab/ci_scripts/setupATLAS.sh
  - echo ${ASETUP_PATH}
  - cd ${CI_PROJECT_DIR}/${ASETUP_PATH}
  - asetup --restore
  - cd ${CI_PROJECT_DIR}
  - echo ${BUILD_PATH}
  - cd ${CI_PROJECT_DIR}/${BUILD_PATH}
  - source */setup.sh
  - cd ../

.switch_tags: &switch_tags
  - git config --global --add safe.directory ${CI_PROJECT_DIR}
  - >
      if [ -f "${CI_PROJECT_DIR}/${ASETUP_PATH}/tag.txt" ]; then
        git config user.email "atlas.top.reconstruction@cern.ch"
        git config user.name "ATLAS Top Reconstruction"
        git config core.filemode false
        git fetch --tags
        git status --porcelain
        git  --no-pager diff
        if  [[ ! `git status --porcelain` ]]; then git stash; fi
        git checkout "tags/$(cat ${CI_PROJECT_DIR}/${ASETUP_PATH}/tag.txt)"
      else
        echo "ERROR: ${ASETUP_PATH}/tag.txt does not exist!"
        exit 1
      fi

.run_top: &run_top
  - set -e
  - cd ${CI_PROJECT_DIR}/${JOBNAME}
  - mkdir ${RUN_DIR}
  - cd ${RUN_DIR}
  - runTop_el.py -i ${INPUTFILE} -o output_${JOBNAME} --particle --parton -e 100 1> log_TopCPToolkit.txt
  - set +e
  - cd ../

.run_top_yaml: &run_top_yaml
  - set -e
  - cd ${CI_PROJECT_DIR}/${JOBNAME}
  - mkdir ${RUN_DIR}
  - cd ${RUN_DIR}
  - runTop_el.py -i ${INPUTFILE} -o output_${JOBNAME} --particle --parton -e 100 -t exampleTtbarLjets 1> log_TopCPToolkit.txt
  - set +e
  - cd ../

.base_job_template:
  stage: run
  tags:
    - cvmfs
  artifacts:
    paths:
      - ${JOBNAME}
    expire_in: 2h
    when: always

.latest_job_template:
  extends: .base_job_template
  script:
    - *prepare_dirs
    - *restore_environment
    - *run_top

.latest_job_yaml_template:
  extends: .base_job_template
  script:
    - *prepare_dirs
    - *restore_environment
    - *run_top_yaml

.reference_job_template:
  extends: .base_job_template
  script:
    - *switch_tags
    - *prepare_dirs
    - *restore_environment
    - *run_top

latestABreleaseRun2:
  extends: .latest_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_latestABreleaseRun2
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_mc20.txt
  needs: [latestABrelease]
  allow_failure: true

latestABreleaseRun2data:
  extends: .latest_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_latestABreleaseRun2data
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_data18.txt
  needs: [latestABrelease]
  allow_failure: true

latestABreleaseRun3:
  extends: .latest_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_latestABreleaseRun3
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_mc21.txt
  needs: [latestABrelease]
  allow_failure: true

latestABreleaseRun3data:
  extends: .latest_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_latestABreleaseRun3data
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_data22.txt
  needs: [latestABrelease]
  allow_failure: true

latestABnightlyRun2:
  extends: .latest_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_latestABnightlyRun2
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_mc20.txt
  needs: [latestABnightly]
  allow_failure: true

latestABnightlyRun3:
  extends: .latest_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_latestABnightlyRun3
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_mc21.txt
  needs: [latestABnightly]
  allow_failure: true

latestABnightlyRun2data:
  extends: .latest_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_latestABnightlyRun2data
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_data18.txt
  needs: [latestABnightly]
  allow_failure: true

latestABnightlyRun3data:
  extends: .latest_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_latestABnightlyRun3data
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_data22.txt
  needs: [latestABnightly]
  allow_failure: true

referenceRun2:
  extends: .reference_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_referenceRun2
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_mc20.txt
  needs: [referenceTopCPToolkitTag]
  allow_failure: true

referenceRun3:
  extends: .reference_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_referenceRun3
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_mc21.txt
  needs: [referenceTopCPToolkitTag]
  allow_failure: true

referenceRun2data:
  extends: .reference_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_referenceRun2data
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_data18.txt
  needs: [referenceTopCPToolkitTag]
  allow_failure: true

referenceRun3data:
  extends: .reference_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_referenceRun3data
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_data22.txt
  needs: [referenceTopCPToolkitTag]
  allow_failure: true

lastweekRun2:
  extends: .reference_job_template
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    JOBNAME: job_lastweekRun2
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_mc20.txt
  needs: [lastweekTopCPToolkitTag]
  allow_failure: true

lastweekRun3:
  extends: .reference_job_template
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    JOBNAME: job_lastweekRun3
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_mc21.txt
  needs: [lastweekTopCPToolkitTag]
  allow_failure: true

lastweekRun2data:
  extends: .reference_job_template
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    JOBNAME: job_lastweekRun2data
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_data18.txt
  needs: [lastweekTopCPToolkitTag]
  allow_failure: true

lastweekRun3data:
  extends: .reference_job_template
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    JOBNAME: job_lastweekRun3data
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_data22.txt
  needs: [lastweekTopCPToolkitTag]
  allow_failure: true

latestABnightlyRun2YAML:
  extends: .latest_job_yaml_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_latestABnightlyRun2YAML
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_mc20.txt
  needs: [latestABnightly]
  allow_failure: true

latestABnightlyRun3YAML:
  extends: .latest_job_yaml_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_latestABnightlyRun3YAML
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_mc21.txt
  needs: [latestABnightly]
  allow_failure: true

latestABnightlyRun2YAMLdata:
  extends: .latest_job_yaml_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_latestABnightlyRun2YAMLdata
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_data18.txt
  needs: [latestABnightly]
  allow_failure: true

latestABnightlyRun3YAMLdata:
  extends: .latest_job_yaml_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_latestABnightlyRun3YAMLdata
    INPUTFILE:  ${CI_PROJECT_DIR}/.gitlab/ci_scripts/input_data22.txt
  needs: [latestABnightly]
  allow_failure: true