stages:
  - validate

variables:
  VAL_DIR: validation
  VAL_DIR_ABS: ${CI_PROJECT_DIR}/${VAL_DIR}

.run_validation: &run_validation
  - set -e
  - mkdir ${VAL_DIR}
  - cd ${VAL_DIR}
  - echo ${REFERENCEFILE}
  - echo ${INPUTFILE}
  - python ${CI_PROJECT_DIR}/.gitlab/ci_scripts/compare_samples.py ${REFERENCEFILE} ${INPUTFILE}

.restore_environment: &restore_environment
  - set +e
  - source ${CI_PROJECT_DIR}/.gitlab/ci_scripts/setupATLAS.sh
  - echo ${ASETUP_PATH}
  - cd ${CI_PROJECT_DIR}/${ASETUP_PATH}
  - asetup --restore
  - cd ${CI_PROJECT_DIR}
  - echo ${BUILD_PATH}
  - cd ${CI_PROJECT_DIR}/${BUILD_PATH}
  - source */setup.sh
  - cd ${CI_PROJECT_DIR}

.base_validation_job_template:
  stage: validate
  tags:
    - cvmfs
  script:
    - *restore_environment
    - *run_validation
  artifacts:
    paths:
      - ${VAL_DIR}
    expire_in: 2h
    when: always
  allow_failure: true


validateRun2:
  extends: .base_validation_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_validateRun2
    REFERENCEFILE: ${CI_PROJECT_DIR}/job_referenceRun2/${RUN_DIR}/output_job_referenceRun2.root
    INPUTFILE: ${CI_PROJECT_DIR}/job_latestABreleaseRun2/${RUN_DIR}/output_job_latestABreleaseRun2.root
  needs: [referenceRun2, latestABreleaseRun2, latestABrelease]

validateRun3:
  extends: .base_validation_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_validateRun3
    REFERENCEFILE: ${CI_PROJECT_DIR}/job_referenceRun3/${RUN_DIR}/output_job_referenceRun3.root
    INPUTFILE: ${CI_PROJECT_DIR}/job_latestABreleaseRun3/${RUN_DIR}/output_job_latestABreleaseRun3.root
  needs: [referenceRun3, latestABreleaseRun3, latestABrelease]

validateRun2data:
  extends: .base_validation_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_validateRun2data
    REFERENCEFILE: ${CI_PROJECT_DIR}/job_referenceRun2data/${RUN_DIR}/output_job_referenceRun2data.root
    INPUTFILE: ${CI_PROJECT_DIR}/job_latestABreleaseRun2data/${RUN_DIR}/output_job_latestABreleaseRun2dataroot
  needs: [referenceRun2data, latestABreleaseRun2data, latestABrelease]

validateRun3data:
  extends: .base_validation_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_validateRun3data
    REFERENCEFILE: ${CI_PROJECT_DIR}/job_referenceRun3data/${RUN_DIR}/output_job_referenceRun3data.root
    INPUTFILE: ${CI_PROJECT_DIR}/job_latestABreleaseRun3data/${RUN_DIR}/output_job_latestABreleaseRun3data.root
  needs: [referenceRun3data, latestABreleaseRun3data, latestABrelease]

validateLastWeekRun2:
  extends: .base_validation_job_template
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    JOBNAME: job_validateLastWeekRun2
    REFERENCEFILE: ${CI_PROJECT_DIR}/job_lastweekRun2/${RUN_DIR}/output_job_lastweekRun2.root
    INPUTFILE: ${CI_PROJECT_DIR}/job_referenceRun2/${RUN_DIR}/output_job_referenceRun2.root
  needs: [referenceRun2, lastweekRun2, latestABrelease]

validateLastWeekRun3:
  extends: .base_validation_job_template
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    JOBNAME: job_validateLastWeekRun3
    REFERENCEFILE: ${CI_PROJECT_DIR}/job_lastweekRun3/${RUN_DIR}/output_job_lastweekRun3.root
    INPUTFILE: ${CI_PROJECT_DIR}/job_referenceRun3/${RUN_DIR}/output_job_referenceRun3.root
  needs: [referenceRun3, lastweekRun3, latestABrelease]

validateLastWeekRun2data:
  extends: .base_validation_job_template
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    JOBNAME: job_validateLastWeekRun2data
    REFERENCEFILE: ${CI_PROJECT_DIR}/job_lastweekRun2data/${RUN_DIR}/output_job_lastweekRun2data.root
    INPUTFILE: ${CI_PROJECT_DIR}/job_referenceRun2data/${RUN_DIR}/output_job_referenceRun2data.root
  needs: [referenceRun2data, lastweekRun2data, latestABrelease]

validateLastWeekRun3data:
  extends: .base_validation_job_template
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    JOBNAME: job_validateLastWeekRun3data
    REFERENCEFILE: ${CI_PROJECT_DIR}/job_lastweekRun3data/${RUN_DIR}/output_job_lastweekRun3data.root
    INPUTFILE: ${CI_PROJECT_DIR}/job_referenceRun3data/${RUN_DIR}/output_job_referenceRun3data.root
  needs: [referenceRun3data, lastweekRun3data, latestABrelease]

validateYAMLRun2:
  extends: .base_validation_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_validateYAMLRun2
    REFERENCEFILE: ${CI_PROJECT_DIR}/job_latestABnightlyRun2/${RUN_DIR}/output_job_latestABnightlyRun2.root
    INPUTFILE: ${CI_PROJECT_DIR}/job_latestABnightlyRun2YAML/${RUN_DIR}/output_job_latestABnightlyRun2YAML.root
  needs: [latestABnightlyRun2, latestABnightlyRun2YAML, latestABnightly]

validateYAMLRun3:
  extends: .base_validation_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_validateYAMLRun3
    REFERENCEFILE: ${CI_PROJECT_DIR}/job_latestABnightlyRun3/${RUN_DIR}/output_job_latestABnightlyRun3.root
    INPUTFILE: ${CI_PROJECT_DIR}/job_latestABnightlyRun3YAML/${RUN_DIR}/output_job_latestABnightlyRun3YAML.root
  needs: [latestABnightlyRun3, latestABnightlyRun3YAML, latestABnightly]

validateYAMLRun2data:
  extends: .base_validation_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_validateYAMLRun2data
    REFERENCEFILE: ${CI_PROJECT_DIR}/job_latestABnightlyRun2data/${RUN_DIR}/output_job_latestABnightlyRun2data.root
    INPUTFILE: ${CI_PROJECT_DIR}/job_latestABnightlyRun2YAMLdata/${RUN_DIR}/output_job_latestABnightlyRun2YAMLdata.root
  needs: [latestABnightlyRun2data, latestABnightlyRun2YAMLdata, latestABnightly]

validateYAMLRun3data:
  extends: .base_validation_job_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
  variables:
    JOBNAME: job_validateYAMLRun3data
    REFERENCEFILE: ${CI_PROJECT_DIR}/job_latestABnightlyRun3data/${RUN_DIR}/output_job_latestABnightlyRun3data.root
    INPUTFILE: ${CI_PROJECT_DIR}/job_latestABnightlyRun3YAMLdata/${RUN_DIR}/output_job_latestABnightlyRun3YAMLdata.root
  needs: [latestABnightlyRun3data, latestABnightlyRun3YAMLdata, latestABnightly]