CommonServices:
  runSystematics: False
  systematicsHistogram: 'listOfSystematics'
  onlySystematicsCategories: # if select only few syst
    - jets
    - electrons
    - muons


PileupReweighting: {}

EventCleaning:
    runEventCleaning: True

Jets:
  - containerName: 'AnaJets'
    jetCollection: 'AntiKt4EMPFlowJets'
    runJvtUpdate: False
    runNNJvtUpdate: True
    runJvtSelection: True
    runGhostMuonAssociation: True
    systematicsModelJES: 'Category'
    systematicsModelJER: 'Full'
    JVT: {}
    PtEtaSelection:
        minPt: 20000.0
        maxEta: 4.5
    FlavourTagging:
      - btagger: 'DL1dv01'
        btagWP: 'FixedCutBEff_77'
        generator: 'autoconfig'
      # - btagger: 'DL1dv01'
      #   btagWP: 'FixedCutBEff_70'
      #   generator: 'autoconfig'
      - btagger: 'DL1dv01'
        btagWP: 'Continuous'
        generator: 'autoconfig'
    FlavourTaggingEventSF:
      - containerName: 'AnaJets.baselineJvt'
        btagger: 'DL1dv01'
        btagWP: 'FixedCutBEff_77'
      - containerName: 'AnaJets.baselineJvt'
        btagger: 'DL1dv01'
        btagWP: 'Continuous'
      # - containerName: 'AnaJets.baselineJvt'
      #   btagger: 'DL1dv01'
      #   btagWP: 'FixedCutBEff_70'

Electrons:
  - containerName: 'AnaElectrons'
    # forceFullSimConfig: True
    crackVeto: True
    IFFClassification: {}
    WorkingPoint:
      - selectionName: 'loose'
        identificationWP: 'TightLH'
        isolationWP: 'NonIso'
        noEffSF: True
      - selectionName: 'tight'
        identificationWP: 'TightLH'
        isolationWP: 'Tight_VarRad'
        noEffSF: True
    PtEtaSelection:
        minPt: 10000.0
        maxEta: 2.47
        useClusterEta: True

Muons:
  - containerName: 'AnaMuons'
    IFFClassification: {}
    WorkingPoint:
      - selectionName: 'loose'
        quality: 'Medium'
        isolation: 'NonIso'
      - selectionName: 'tight'
        quality: 'Medium'
        isolation: 'Tight_VarRad'
        systematicBreakdown: True
    PtEtaSelection:
        minPt: 10000.0
        maxEta: 2.5

GeneratorLevelAnalysis: {}

MissingET:
  - containerName: 'AnaMET'
    # Format should follow Object: '<containerName>.<postfix>'
    jets: 'AnaJets'
    electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'

OverlapRemoval:
  inputLabel: 'preselectOR'
  outputLabel: 'passesOR'
  # Format should follow Object: '<containerName>.<postfix>'
  jets: 'AnaJets.baselineJvt'
  electrons: 'AnaElectrons.tight'
  muons: 'AnaMuons.tight'
  boostedLeptons: True # UseSlidingDR

# OverlapRemoval:
#   - inputLabel: 'preselectORloose'
#     outputLabel: 'passesORloose'
#     jets: 'AnaJets.baselineJvt'
#     electrons: 'AnaElectrons.loose'
#     muons: 'AnaMuons.loose'
#     electronsSelectionName: 'loose'
#     muonsSelectionName: 'loose'
#     jetsSelectionName: 'baselineJvtLoose'
#     addPreselection: True
#   - inputLabel: 'preselectORtight'
#     outputLabel: 'passesORtight'
#     jets: 'AnaJets.baselineJvt'
#     electrons: 'AnaElectrons.tight'
#     muons: 'AnaMuons.tight'
#     electronsSelectionName: 'tight'
#     muonsSelectionName: 'tight'
#     jetsSelectionName: 'baselineJvtTight'
#     addPreselection: True

ObjectCutFlow:
  - containerName: 'AnaElectrons'
    selectionName: 'tight'
  - containerName: 'AnaJets'
    selectionName: 'baselineJvt'
  - containerName: 'AnaMuons'
    selectionName: 'tight'

Thinning:
  - containerName: 'AnaJets'
    outputName: 'OutJets'
    selectionName: 'baselineJvt'
  - containerName: 'AnaElectrons'
    outputName: 'OutElectrons'
    selectionName: 'tight||loose'
  - containerName: 'AnaMuons'
    outputName: 'OutMuons'
    selectionName: 'tight||loose'

LeptonSF:
  # - electrons: 'AnaElectrons.tight'
  - muons: 'AnaMuons.tight'
    lepton_postfix: 'tight'

Trigger:
    triggerChainsPerYear:
      '2015':
        - 'HLT_e24_lhmedium_L1EM20VH || HLT_e60_lhmedium || HLT_e120_lhloose '
        # - 'HLT_2e12_lhloose_L12EM10VH'
        - 'HLT_mu20_iloose_L1MU15 || HLT_mu40'
      '2016':
        - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
        # - 'HLT_2e17_lhvloose_nod0'
        - 'HLT_mu26_ivarmedium || HLT_mu50'
      '2017':
        - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
        # - 'HLT_2e24_lhvloose_nod0'
        - 'HLT_mu26_ivarmedium || HLT_mu50'
      '2018':
        - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
        # - 'HLT_2e24_lhvloose_nod0'
        # - 'HLT_2e17_lhvloose_nod0_L12EM15VHI'
        - 'HLT_mu26_ivarmedium || HLT_mu50'

    noFilter: False
    electrons: 'AnaElectrons.tight'
    electronID: 'Tight'
    electronIsol: 'Tight_VarRad'
    muons: 'AnaMuons.tight'
    muonID: 'Medium'

EventSelection:
  - electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    jets: 'AnaJets.baselineJvt'
    met: 'AnaMET'
    btagDecoration: 'ftag_select_DL1dv01_FixedCutBEff_77'
    noFilter: False
    cutFlowHistograms: True
    selectionCutsDict:
      'SUBcommon': |
        JET_N_BTAG DL1dv01:FixedCutBEff_77 >= 0
        JET_N 20000 >= 1
        #MET >= 20000
        SAVE
      # 'ejets': |
      #   IMPORT SUBcommon
      #   EL_N 25000 >= 1
      #   EL_N tight 25000 == 1
      #   MU_N 25000 == 0
      #   SAVE
      # 'mujets': |
      #   IMPORT SUBcommon
      #   EL_N 25000 == 0
      #   MU_N 25000 == 1
      #   SAVE
      'emu': |
        IMPORT SUBcommon
        EL_N 10000 >= 1
        EL_N tight 10000 == 1
        MU_N tight 10000 == 1
        SAVE

      'eemu': |
        IMPORT SUBcommon
        EL_N 10000 >= 2
        EL_N tight 10000 == 2
        MU_N 10000 == 1
        SAVE
      'mumue': |
        IMPORT SUBcommon
        EL_N 10000 >= 1
        EL_N tight 10000 == 1
        MU_N 10000 == 2
        SAVE
      'eee': |
        IMPORT SUBcommon
        EL_N 10000 >= 3
        EL_N tight 10000 == 3
        SAVE

      'mumumu': |
        IMPORT SUBcommon
        MU_N 10000 == 3
        SAVE


PartonHistory:
  - histories: 'Ttbar'

    #ParticleLevel:
    #useTruthJets: True
    #useTruthElectrons: False
    #useTruthMuons: False
    #doOverlapRemoval: False
    #elPtMin: 25000.
    #muPtMin: 25000.
    #jetPtMin: 25000.
    #jetEtaMax: 2.5


# After configuring each container, many variables will be saved automatically.
Output:
  treeName: 'reco'
  # vars: 
  #   - 'OutMuons_NOSYS.truthOrigin -> mu_truthOrigin'
  #   - 'OutElectrons_NOSYS.truthOrigin -> el_truthOrigin'
  vars: [OutJets_NOSYS.HadronConeExclTruthLabelID -> jet_TruthFlavour, OutJets_NOSYS.HadronConeExclExtendedTruthLabelID -> jet_TruthFlavouExtended]
  #vars: []
  metVars: []
  containers:
      # Format should follow: '<suffix>:<output container>'
      el_: 'OutElectrons'
      mu_: 'OutMuons'
      jet_: 'OutJets'
      met_: 'AnaMET'
      '': 'EventInfo'
        #'parton_': 'TopPartonHistoryTtbar'
        #'truth_jet_': 'ParticleLevelJets'

  commands:
    # Turn output branches on and off with 'enable' and 'disable'
     - enable trigPassed_HLT_e*
     - enable pass*
    # per-jet jvt and b-tag SFs, store only per-event
    # - 'disable jet_jvtEfficiency.*'
    # - 'disable jet_.*._eff.*'

AddConfigBlocks:
    - modulePath: 'TopCPToolkit.KLFitterConfig'
      functionName: 'KLFitterConfig'
      algName: 'KLFitter'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.TopSpaNetConfig'
      functionName: 'TopSpaNetConfig'
      algName: 'SpaNet'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.particleLevelConfig'
      functionName: 'particleLevelConfig'
      algName: 'ParticleLevel'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.truthConfig'
      functionName: 'truthConfig'
      algName: 'PartonHistory'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.TtbarNNLORecursiveRewConfig'
      functionName: 'TtbarNNLORecursiveRewConfig'
      algName: 'TtbarNNLO'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.JetMatchingConfig'
      functionName: 'JetMatchingConfig'
      algName: 'JetMatching'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.PartonToJetsMatchConfig'
      functionName: 'PartonToJetsMatchConfig'
      algName: 'PartonToJetsMatch'
      pos: 'Output'
    # - modulePath: 'TopCPToolkit.LeptonSFCalculatorConfig'
    #   functionName: 'LeptonSFCalculatorConfig'
    #   algName: 'LeptonSF'
    #   pos: 'Output'
    # - modulePath: 'TopCPToolkit.HiggsTruthMatchingConfig'
    #   functionName: 'HiggsTruthMatchingConfig'
    #   algName: 'HiggsTruthMatchingInfo'
    #   pos: 'Output'
    # - modulePath: 'TopCPToolkit.IOStatsConfig'
    #   functionName: 'IOStatsConfig'
    #   algName: 'IOStats'
