CommonServices: {}

GeneratorLevelAnalysis: {}

ParticleLevel:
  useTruthLargeRJets: True
  useTruthPhotons: True
  useTruthTaus: True

# After configuring each container, many variables will be saved automatically.
Output:
  treeName: 'particleLevel'
  vars:
    - 'EventInfo.mcChannelNumber -> mcChannelNumber'
    - 'EventInfo.runNumber -> runNumber'
    - 'EventInfo.eventNumber -> eventNumber'
  metVars: []
  metTermName: 'NonInt'
  containers:
      # Format should follow: '<suffix>:<output container>'
      '': 'EventInfo'
      'el_': 'ParticleLevelElectrons'
      'mu_': 'ParticleLevelMuons'
      'ph_': 'ParticleLevelPhotons'
      'tau_': 'ParticleLevelTaus'
      'jet_': 'ParticleLevelJets'
      'ljet_': 'ParticleLevelLargeRJets'
      'met_': 'ParticleLevelMissingET'

AddConfigBlocks:
    - modulePath: 'TopCPToolkit.particleLevelConfig'
      functionName: 'particleLevelConfig'
      algName: 'ParticleLevel'
      pos: 'Output'
