CommonServices:
  systematicsHistogram: 'listOfSystematics'

PileupReweighting: {}

EventCleaning:
    runEventCleaning: True

Jets:
  - containerName: 'AnaJets'
    jetCollection: 'AntiKt4EMPFlowJets'
    runJvtUpdate: False
    runNNJvtUpdate: True
    runGhostMuonAssociation: True
    systematicsModelJES: 'Category'
    systematicsModelJER: 'Full'
    JVT: {}
    PtEtaSelection:
        minPt: 25000.0
        maxEta: 2.5
    FlavourTagging:
      - btagger: 'DL1dv01'
        btagWP: 'Continuous'
        generator: 'autoconfig'
        minPt: 25000.0
      # - btagger: 'GN2v00LegacyWP'
      #   btagWP: 'Continuous'
      #   generator: 'autoconfig'
      #   minPt: 25000.0
      #   bTagCalibFile: '/cvmfs/atlas.cern.ch/repo/sw/database/GroupData/xAODBTaggingEfficiency/13TeV/2023-22-13TeV-MC20-CDI_Test_2023-08-1_v1.root'

Electrons:
  - containerName: 'AnaElectrons'
    crackVeto: True
    forceFullSimConfig: True
    WorkingPoint:
      - selectionName: 'tight'
        likelihoodWP: 'MediumLH'
        isolationWP: 'Loose_VarRad'
    PtEtaSelection:
        minPt: 5000.0
        maxEta: 2.47

Muons:
  - containerName: 'AnaMuons'
    WorkingPoint:
      - selectionName: 'tight'
        quality: 'Medium'
        isolation: 'Loose_VarRad'
    PtEtaSelection:
        minPt: 5000.0
        maxEta: 2.5

PerEventSF:
  - name: 'btagSFCalc_DL1dv01_Continuous'
    particles: 'AnaJets.jvt'
    objectSF: 'ftag_effSF_DL1dv01_Continuous_%SYS%'
    eventSF: 'weight_btagSF_DL1dv01_Continuous_%SYS%'
  # - name: 'btagSFCalc_GN2v00LegacyWP_Continuous'
  #   particles: 'AnaJets.jvt'
  #   objectSF: 'ftag_effSF_GN2v00LegacyWP_Continuous_%SYS%'
  #   eventSF: 'weight_btagSF_GN2v00LegacyWP_Continuous_%SYS%'

LeptonSF:
  - electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    lepton_postfix: 'tight'

GeneratorLevelAnalysis: {}

# containerName and postfix must be defined in their respective blocks
MissingET:
  - containerName: 'AnaMET'
    # Format should follow Object: '<containerName>.<postfix>'
    jets: 'AnaJets'
    electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'

# containerName and postfix must be defined in their respective blocks
OverlapRemoval:
  inputLabel: 'preselectOR'
  outputLabel: 'passesOR'
  # Format should follow Object: '<containerName>.<postfix>'
  jets: 'AnaJets.jvt'
  electrons: 'AnaElectrons.tight'
  muons: 'AnaMuons.tight'

Thinning:
  - containerName: 'AnaJets'
    outputName: 'OutJets'
    selectionName: 'jvt&&passesOR'
  - containerName: 'AnaElectrons'
    outputName: 'OutElectrons'
    selectionName: 'tight'
  - containerName: 'AnaMuons'
    outputName: 'OutMuons'
    selectionName: 'tight'

ExtraParticleDecoration:
   - name: 'El'
     particles: 'AnaElectrons'
   - name: 'Mu'
     particles: 'AnaMuons'
   - name: 'Jets'
     particles: 'AnaJets'

Trigger:
    triggerChainsPerYear:
        '2015':
            - 'HLT_e24_lhmedium_L1EM20VH || HLT_e60_lhmedium || HLT_e120_lhloose'
            - 'HLT_mu20_iloose_L1MU15 || HLT_mu50'
        '2016':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
            - 'HLT_mu26_ivarmedium || HLT_mu50'
        '2017':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
            - 'HLT_mu26_ivarmedium || HLT_mu50'
        '2018':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
            - 'HLT_mu26_ivarmedium || HLT_mu50'
        '2022':
            - 'HLT_e26_lhtight_ivarloose_L1EM22VHI || HLT_e60_lhmedium_L1EM22VHI || HLT_e140_lhloose_L1EM22VHI'
            - 'HLT_mu26_ivarmedium_L1MU14FCH || HLT_mu50_L1MU14FCH'
    noFilter: False
    electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    electronID: 'Tight'
    electronIsol: 'Tight_VarRad'
    muonID: 'Medium'

EventSelection:
  - electrons: 'AnaElectrons.tight&&passesOR'
    muons: 'AnaMuons.tight&&passesOR'
    jets: 'AnaJets.jvt&&passesOR'
    met: 'AnaMET'
    noFilter: False
    cutFlowHistograms: True
    selectionCutsDict:
      'SUBcommon': |
        JET_N 25000 >= 2
        SUM_EL_N_MU_N 25000 >= 1
        SUM_EL_N_MU_N 5000 == 2
        OS
        SAVE
      'ee': |
        EL_N 5000 == 2
        MU_N 5000 == 0
        SAVE
      'em': |
        EL_N 5000 == 1
        MU_N 5000 == 1
        SAVE
      'mm': |
        EL_N 5000 == 0
        MU_N 5000 == 2
        SAVE

PartonHistory:
  - histories: 'Ttbar'

# After configuring each container, many variables will be saved automatically.
Output:
  treeName: 'reco'
  vars: []
  metVars: []
  containers:
      # Format should follow: '<suffix>:<output container>'
      mu_: 'OutMuons'
      el_: 'OutElectrons'
      jet_: 'OutJets'
      met_: 'AnaMET'
      '': 'EventInfo'
      'Ttbar_': 'TopPartonHistoryTtbar'
  commands:
      # Turn output branches on and off with 'enable' and 'disable'
      - disable jet_.*_eff.*
      - disable jet_jvtEfficiency.*
      - disable trigPassed_HLT.*
      - disable Ttbar_MC.*before.*
      - disable Ttbar_MC.*SC.*
      - disable met_sumet.*
      - disable globalTriggerMatch
      - disable el_select_tight.*
      - disable mu_select_tight.*
      - disable jet_select_jvt.*
      - disable pass_SUBcommon.*
      - disable el.*effSF.*
      - disable mu.*effSF.*
