CommonServices: {}

GeneratorLevelAnalysis: {}

PartonHistory:
  - histories: 'Ttbar.TtbarLight'

TtbarNNLO: {}

# After configuring each container, many variables will be saved automatically.
Output:
  treeName: 'truth'
  vars:
    - 'EventInfo.mcChannelNumber -> mcChannelNumber'
    - 'EventInfo.runNumber -> runNumber'
    - 'EventInfo.eventNumber -> eventNumber'
  containers:
      # Format should follow: '<suffix>:<output container>'
      '': 'EventInfo'
      'Ttbar_': 'TopPartonHistoryTtbar'
      'TtbarLight_': 'TopPartonHistoryTtbarLight'
