CommonServices:
  systematicsHistogram: 'listOfSystematics'

PileupReweighting: {}

EventCleaning:
    runEventCleaning: True

Jets:
  - containerName: 'AnaJets'
    jetCollection: 'AntiKt4EMPFlowJets'
    runJvtUpdate: False
    runNNJvtUpdate: True
    runGhostMuonAssociation: True
    systematicsModelJES: 'Category'
    systematicsModelJER: 'Full'
    JVT: {}
    PtEtaSelection:
        minPt: 20000.0
        maxEta: 2.5
    FlavourTagging:
      # GN2 v01
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_85'
        generator: 'autoconfig'
        bTagCalibFile : /cvmfs/atlas.cern.ch/repo/sw/database/GroupData/xAODBTaggingEfficiency/13p6TeV/2021-22-13TeV-MC21-CDI_GN2v01_Test_smooth.root
        noEffSF : True
        # Add tag scores to the output
        saveScores: 'All'
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_77'
        generator: 'autoconfig'
        bTagCalibFile : /cvmfs/atlas.cern.ch/repo/sw/database/GroupData/xAODBTaggingEfficiency/13p6TeV/2021-22-13TeV-MC21-CDI_GN2v01_Test_smooth.root
        noEffSF : True
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_70'
        generator: 'autoconfig'
        bTagCalibFile : /cvmfs/atlas.cern.ch/repo/sw/database/GroupData/xAODBTaggingEfficiency/13p6TeV/2021-22-13TeV-MC21-CDI_GN2v01_Test_smooth.root
        noEffSF : True
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_65'
        generator: 'autoconfig'
        bTagCalibFile : /cvmfs/atlas.cern.ch/repo/sw/database/GroupData/xAODBTaggingEfficiency/13p6TeV/2021-22-13TeV-MC21-CDI_GN2v01_Test_smooth.root
        noEffSF : True
        # Add SV Mass to the output
        saveCustomVariables: ['SV1_masssvx']

Electrons:
  - containerName: 'AnaElectrons'
    crackVeto: True
    WorkingPoint:
      - selectionName: 'loose'
        identificationWP: 'TightLH'
        isolationWP: 'Loose_VarRad'
      - selectionName: 'tight'
        identificationWP: 'TightLH'
        isolationWP: 'Tight_VarRad'
    PtEtaSelection:
        minPt: 25000.0
        maxEta: 2.47
        useClusterEta: True

# Photons:
#   - containerName: 'AnaPhotons'
#     recomputeIsEM: False
#     WorkingPoint:
#       - selectionName: 'loose'
#         qualityWP: 'Loose'
#         isolationWP: 'Undefined'
#         recomputeIsEM: False
#       - selectionName: 'tight'
#         qualityWP: 'Tight'
#         isolationWP: 'FixedCutTight'
#         recomputeIsEM: False
#     PtEtaSelection:
#         minPt: 25000.0
#         maxEta: 2.5
#         useClusterEta: True

Muons:
  - containerName: 'AnaMuons'
    WorkingPoint:
      - selectionName: 'loose'
        quality: 'Medium'
        isolation: 'Loose_VarRad'
      - selectionName: 'tight'
        quality: 'Medium'
        isolation: 'Tight_VarRad'
        systematicBreakdown: True
    PtEtaSelection:
        minPt: 25000.0
        maxEta: 2.5

# TauJets:
#   - containerName: 'AnaTauJets'
#     WorkingPoint:
#       - selectionName: 'tight'
#         quality: 'Tight'
#     PtEtaSelection:
#         minPt: 25000.0
#         maxEta: 2.5

GeneratorLevelAnalysis: {}

# containerName and postfix must be defined in their respective blocks
OverlapRemoval:
  inputLabel: 'preselectOR'
  outputLabel: 'passesOR'
  # Format should follow Object: '<containerName>.<postfix>'
  jets: 'AnaJets.baselineJvt'
  #taus: 'AnaTauJets.tight'
  electrons: 'AnaElectrons.tight'
  #photons: 'AnaPhotons.tight'
  muons: 'AnaMuons.tight'

# containerName and postfix must be defined in their respective blocks
MissingET:
  - containerName: 'AnaMET'
    # Format should follow Object: '<containerName>.<postfix>'
    jets: 'AnaJets'
    #taus: 'AnaTauJets.tight'
    electrons: 'AnaElectrons.tight'
    #photons: 'AnaPhotons.tight&&selectPtEta'
    muons: 'AnaMuons.tight'


ObjectCutFlow:
  - containerName: 'AnaElectrons'
    selectionName: 'tight'
  - containerName: 'AnaMuons'
    selectionName: 'tight'
  # - containerName: 'AnaTauJets'
  #   selectionName: 'tight'
  # - containerName: 'AnaPhotons'
  #   selectionName: 'tight'
  - containerName: 'AnaJets'
    selectionName: 'baselineJvt'

Thinning:
  - containerName: 'AnaJets'
    outputName: 'OutJets'
    selectionName: 'baselineJvt'
  - containerName: 'AnaElectrons'
    outputName: 'OutElectrons'
    selectionName: 'tight||loose'
  # - containerName: 'AnaPhotons'
  #   outputName: 'OutPhotons'
  #   selectionName: 'tight||loose'
  - containerName: 'AnaMuons'
    outputName: 'OutMuons'
    selectionName: 'tight||loose'
  # - containerName: 'AnaTauJets'
  #   outputName: 'OutTauJets'
  #   selectionName: 'tight'

#LeptonSF:
#  - electrons: 'AnaElectrons.tight'
#    muons: 'AnaMuons.tight'
#    lepton_postfix: 'tight'

Trigger:
    triggerChainsPerYear:
        '2015':
            - 'HLT_e24_lhmedium_L1EM20VH || HLT_e60_lhmedium || HLT_e120_lhloose'
            - 'HLT_mu20_iloose_L1MU15 || HLT_mu40'
        '2016':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
            - 'HLT_mu26_ivarmedium || HLT_mu50'
        '2017':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
            - 'HLT_mu26_ivarmedium || HLT_mu50'
        '2018':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
            - 'HLT_mu26_ivarmedium || HLT_mu50'
        '2022':
            - 'HLT_e26_lhtight_ivarloose_L1EM22VHI || HLT_e60_lhmedium_L1EM22VHI || HLT_e140_lhloose_L1EM22VHI'
            - 'HLT_mu24_ivarmedium_L1MU14FCH || HLT_mu50_L1MU14FCH'
    noFilter: False
    electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    electronID: 'Tight'
    electronIsol: 'Tight_VarRad'
    muonID: 'Medium'

EventSelection:
  - electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    jets: 'AnaJets.baselineJvt'
    met: 'AnaMET'
    btagDecoration: 'ftag_select_DL1dv01_FixedCutBEff_85'
    noFilter: True
    cutFlowHistograms: True
    selectionCutsDict:
     'SUBcommon': |
       JET_N_BTAG GN2v01:FixedCutBEff_85 >= 1
       JET_N 20000 == 4
       MET >= 20000
       SAVE
     'ejets': |
       IMPORT SUBcommon
       EL_N 25000 >= 1
       MU_N 25000 == 0
       SAVE
     'mujets': |
       IMPORT SUBcommon
       EL_N 25000 == 0
       MU_N 25000 >= 1
       SAVE
     'emu': |
       EL_N 25000 == 1
       MU_N 25000 == 1
       JET_N 20000 >= 2
       SAVE
     'dielec': |
       EL_N 28000 >= 1
       EL_N 18000 == 2
       MU_N 18000 == 0
       OS
       MLL > 81000
       MLL < 101000
       SAVE
     'dimuon': |
       MU_N 28000 >= 1
       MU_N 18000 == 2
       EL_N 18000 == 0
       OS
       MLL > 81000
       MLL < 101000
       SAVE

KLFitter:
  - containerName: 'KLFitterResult'
    electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    jets: 'AnaJets.baselineJvt'
    met: 'AnaMET'
    likelihoodType: 'ttbar'
    jetSelectionMode: 'kLeadingFour'
    btaggingMethod: 'kNotag'
    bTagCDIFile: /cvmfs/atlas.cern.ch/repo/sw/database/GroupData/xAODBTaggingEfficiency/13p6TeV/2021-22-13TeV-MC21-CDI_GN2v01_Test_smooth.root
    btagger: 'GN2v01'
    btagWP: 'FixedCutBEff_85'
    selectionRegionsConfig: 'selectionName:pass_ejets, leptonType: kElectron;selectionName:pass_mujets, leptonType: kMuon'

SpaNet:
  - topology: 'TtbarLjets'
    electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    jets: 'AnaJets.baselineJvt'
    met: 'AnaMET'
    eventSelection: 'pass_ejets_%SYS%,as_char||pass_mujets_%SYS%,as_char'
  - topology: 'TtbarLjetsNu'
    electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    jets: 'AnaJets.baselineJvt'
    met: 'AnaMET'
    eventSelection: 'pass_ejets_%SYS%,as_char||pass_mujets_%SYS%,as_char'

Bootstraps:
  nReplicas: 2000
  runOnMC: True

# After configuring each container, many variables will be saved automatically.
Output:
  treeName: 'reco'
  vars: [OutJets_NOSYS.HadronConeExclTruthLabelID -> jet_TruthFlavour, OutJets_NOSYS.HadronConeExclExtendedTruthLabelID -> jet_TruthFlavouExtended,
  KLFitterResult_%SYS%.model_bhad_jetIndex -> b_from_tophad_jetIndex_%SYS%, KLFitterResult_%SYS%.model_blep_jetIndex -> b_from_toplep_jetIndex_%SYS%,
  KLFitterResult_%SYS%.model_lq1_jetIndex -> jet1_from_W_jetIndex_%SYS%, KLFitterResult_%SYS%.model_lq2_jetIndex -> jet2_from_W_jetIndex_%SYS%]
  metVars: []
  containers:
      # Format should follow: '<suffix>:<output container>'
      mu_: 'OutMuons'
      el_: 'OutElectrons'
      # ph_: 'OutPhotons'
      # tau_: 'OutTauJets'
      jet_: 'OutJets'
      met_: 'AnaMET'
      klfitter_: 'KLFitterResult'
      '': 'EventInfo'

AddConfigBlocks:
    - modulePath: 'TopCPToolkit.KLFitterConfig'
      functionName: 'KLFitterConfig'
      algName: 'KLFitter'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.TopSpaNetConfig'
      functionName: 'TopSpaNetConfig'
      algName: 'SpaNet'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.particleLevelConfig'
      functionName: 'particleLevelConfig'
      algName: 'ParticleLevel'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.truthConfig'
      functionName: 'truthConfig'
      algName: 'PartonHistory'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.TtbarNNLORecursiveRewConfig'
      functionName: 'TtbarNNLORecursiveRewConfig'
      algName: 'TtbarNNLO'
      pos: 'Output'
